# Generated by Django 6.0.3 on 2026-03-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('estudiante', 'Estudiante'), ('desarrollador', 'Desarrollador')], default='estudiante', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('estado', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('racha', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=10)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'managed': True,
            },
        ),
    ]
