# Generated by GitHub Copilot on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoEmitido',
            fields=[
                ('certificate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('general', 'General'), ('curso', 'Curso')], default='general', max_length=20)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('total_courses', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_generados', to='courses.curso')),
                ('issued_by', models.ForeignKey(blank=True, db_column='issued_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to='users.usuario')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificados_recibidos', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Certificado emitido',
                'verbose_name_plural': 'Certificados emitidos',
                'db_table': 'certificados_emitidos',
                'ordering': ['-issued_at'],
                'managed': True,
            },
        ),
    ]
