# Generated by Django 6.0.3 on 2026-03-26 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15, null=True)),
                ('estado', models.IntegerField(blank=True, default=0, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'db_table': 'lecciones',
                'ordering': ['orden'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
                'db_table': 'lenguajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado')], default='en_progreso', max_length=15)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('puntaje', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Progreso de Usuario',
                'verbose_name_plural': 'Progresos de Usuarios',
                'db_table': 'progreso_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='courses.curso')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripciones',
                'managed': True,
                'unique_together': {('user', 'course')},
            },
        ),
    ]
